eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: epass-2c-zuul
zuul:
  routes:
    api-a:
      path: /epass-api/**
      serviceId: epass-2c-feigh
